baseURL: /
title: Nils Fahldieck · Solutions Engineer
theme: hugo-coder

defaultContentLanguage: en

params:
  avatarURL: images/avatar.jpg
  author: Nils Fahldieck
  description: Nils Fahldieck · Solutions Engineer
  info: Multi-cloud adoption is possible!

  hideColorSchemeToggle: false
  colorScheme: auto

  hideCopyright: true
  footerContent: |
    Photo by <a href="https://www.tobiaskoch.net/">Tobias Koch</a>.

  keywords: >-
    Nils Fahldieck,
    Rabattkarte,
    administrator,
    Amazon,
    AWS,
    Azure,
    cloud-native,
    cloud,
    consultancy,
    consultant,
    DevOps,
    k8s,
    Kubernetes,
    Linux,
    Microsoft,
    HashiCorp

  social:
    - icon: fa fa-github
      name: GitHub
      url: https://github.com/Rabattkarte
      weight: 10
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://linkedin.com/in/nfahldieck
      weight: 30
    - icon: fa fa-xing
      name: Xing
      url: https://xing.com/profile/Nils_Fahldieck
      weight: 40
    - icon: fa fa-medium
      name: Medium
      url: https://rabattkarte.medium.com
      weight: 41
    - icon: fa fa-trophy
      name: Credly
      url: https://www.credly.com/users/nils-fahldieck/badges
      weight: 50
    - icon: fa fa-envelope
      name: E-mail
      url: mailto:nils@fahldieck.de
      weight: 70
