baseURL: /
title: Nils Fahldieck · Senior Multi-Cloud Consultant
theme: hugo-coder

defaultContentLanguage: en

params:
  avatarURL: images/avatar.jpg
  author: Nils Fahldieck
  description: Nils Fahldieck · Senior Multi-Cloud Consultant
  info: I am on a journey to make cloud-native the new normal

  hideColorSchemeToggle: false
  colorScheme: auto

  hideCopyright: true
  footerContent: |
    Photo by <a href="https://www.tobiaskoch.net/">Tobias Koch</a>.

  keywords: >-
    Nils Fahldieck,
    Rabattkarte,
    administrator,
    Amazon,
    AWS,
    Azure,
    cloud-native,
    cloud,
    consultancy,
    consultant,
    DevOps,
    k8s,
    Kubernetes,
    Linux,
    Microsoft

  social:
    - icon: fa fa-github
      name: GitHub
      url: https://github.com/Rabattkarte
      weight: 10
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://linkedin.com/in/nfahldieck
      weight: 30
    - icon: fa fa-xing
      name: Xing
      url: https://xing.com/profile/Nils_Fahldieck
      weight: 40
    - icon: fa fa-trophy
      name: Twitter
      url: https://www.credly.com/users/nils-fahldieck/badges
      weight: 50
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/rabattkarte
      weight: 60
    - icon: fa fa-envelope
      name: fa fa-mail
      url: mailto:nils@fahldieck.de
      weight: 70
